'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ActivityDetail
    Public Property user_id As Integer
    Public Property activity_id As Integer
    Public Property CCY As String
    Public Property rate As Nullable(Of Decimal)
    Public Property Cost As Decimal

    Public Overridable Property Activity As Activity
    Public Overridable Property UserAccount As UserAccount

End Class
