'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ExchangeRate
    Public Property SEQ As Integer
    Public Property FY As Integer
    Public Property MONTH As Integer
    Public Property CCY As String
    Public Property RATE As Decimal

End Class
