'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class UserAccount

    <Key>
    <Display(Name:="User ID")>
    Public Property user_id As Integer

    <Display(Name:="First Name")>
    <Required(ErrorMessage:="First Name is required.")>
    Public Property first_name As String

    <Display(Name:="Last Name")>
    <Required(ErrorMessage:="Last Name is required.")>
    Public Property last_name As String

    <Display(Name:="User Name")>
    <Required(ErrorMessage:="User Name is required.")>
    Public Property username As String

    <Display(Name:="Gender")>
    <Required(ErrorMessage:="Gender is required.")>
    Public Property gender As String

    <Display(Name:="Email")>
    <Required(ErrorMessage:="Email is required.")>
    Public Property email As String

    <Display(Name:="Password")>
    <Required(ErrorMessage:="Password is required.")>
    <DataType(DataType.Password)>
    Public Property password As String

    <Display(Name:="Confirm Password")>
    <Required(ErrorMessage:="Confirm Password is required.")>
    <DataType(DataType.Password)>
    <Compare("password", ErrorMessage:="Password not match.")>
    Public Property confirmpassword As String

End Class
