'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

<MetadataType(GetType(UserAccountMetaData))>
Partial Public Class UserAccount
    Public Property user_id As Integer
    Public Property first_name As String
    Public Property last_name As String
    Public Property username As String
    Public Property gender As String
    Public Property email As String
    Public Property password As String
    Public Property confirmpassword As String

    Public Overridable Property ActivityDetails As ICollection(Of ActivityDetail) = New HashSet(Of ActivityDetail)

End Class

Public Class UserAccountMetaData

    <DataType(DataType.Password)>
    Public Property password As String

    <DataType(DataType.Password)>
    <Compare("password", ErrorMessage:="Username or Password not match.")>
    Public Property confirmpassword As String
End Class